ui__tab__settings__users <- function(ses) { html__tab__settings(ses = ses, tbl_name = "users") }
ui__tab__settings__models <- function(ses) { html__tab__settings(ses = ses, tbl_name = "models") }
ui__tab__settings__datasets <- function(ses) { html__tab__settings(ses = ses, tbl_name = "datasets") }
ui__tab__settings__papers <- function(ses) { html__tab__settings(ses = ses, tbl_name = "papers") }
ui__tab__settings__settings <- function(ses) { html__tab__settings(ses = ses, tbl_name = "settings") }
ui__tab__settings__appstate <- function(ses) { html__tab__settings(ses = ses, tbl_name = "appstate") }
ui__tab__settings__modeltypes <- function(ses) { html__tab__settings(ses = ses, tbl_name = "modeltypes") }
ui__tab__settings__datatypes <- function(ses) { html__tab__settings(ses = ses, tbl_name = "datatypes") }
ui__tab__settings__platforms <- function(ses) { html__tab__settings(ses = ses, tbl_name = "platforms") }
ui__tab__settings__mapping_users_groups <- function(ses) { html__tab__settings(ses = ses, tbl_name = "mapping_users_groups") }
ui__tab__settings__mapping_users_settings <- function(ses) { html__tab__settings(ses = ses, tbl_name = "mapping_users_settings") }
ui__tab__settings__mapping_users_models <- function(ses) { html__tab__settings(ses = ses, tbl_name = "mapping_users_models") }
ui__tab__settings__mapping_users_datasets <- function(ses) { html__tab__settings(ses = ses, tbl_name = "mapping_users_datasets") }
ui__tab__settings__mapping_users_resources <- function(ses) { html__tab__settings(ses = ses, tbl_name = "mapping_users_resources") }
ui__tab__settings__mapping_users_sessions <- function(ses) { html__tab__settings(ses = ses, tbl_name = "mapping_users_sessions") }
ui__tab__settings__mapping_groups_models <- function(ses) { html__tab__settings(ses = ses, tbl_name = "mapping_groups_models") }
ui__tab__settings__mapping_groups_settings <- function(ses) { html__tab__settings(ses = ses, tbl_name = "mapping_groups_settings") }
ui__tab__settings__mapping_groups_datasets <- function(ses) { html__tab__settings(ses = ses, tbl_name = "mapping_groups_datasets") }
ui__tab__settings__mapping_groups_resources <- function(ses) { html__tab__settings(ses = ses, tbl_name = "mapping_groups_resources") }
ui__tab__settings__mapping_papers_models <- function(ses) { html__tab__settings(ses = ses, tbl_name = "mapping_papers_models") }
ui__tab__settings__mapping_papers_datasets <- function(ses) { html__tab__settings(ses = ses, tbl_name = "mapping_papers_datasets") }
ui__tab__settings__mapping_datasets_features <- function(ses) { html__tab__settings(ses = ses, tbl_name = "mapping_datasets_features") }
ui__tab__settings__mapping_models_features <- function(ses) { html__tab__settings(ses = ses, tbl_name = "mapping_models_features") }
ui__tab__settings__mapping_models_classes <- function(ses) { html__tab__settings(ses = ses, tbl_name = "mapping_models_classes") }
ui__tab__settings__mapping_models_datasets <- function(ses) { html__tab__settings(ses = ses, tbl_name = "mapping_models_datasets") }
